<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Stocks  %sAnalysis%s'), '<span class="zf-green">', '</span>') ?></h1>
    <br/>
    <p><?php echo sprintf($this->translate('<strong>Disclaimer: </strong>This is a private application meant for
		use by Mr. R. Prabhakar Rao only. Please exit if you are not authorized to
		use this application. Thanks!'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
    <br/>
    <p>     <a class="btn btn-success btn-lg"  href="<?php echo $this->url('stocks');?>">Enter</a> </p>
    </div>
<br />
<br />
<br />
