CREATE TABLE `SCRIP` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SYMBOL` varchar(45) DEFAULT NULL,
  `SERIES` char(2) DEFAULT NULL,
  `CREATED_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1672 DEFAULT CHARSET=latin1;