CREATE TABLE `stocks` (
  `LAST` float NOT NULL,
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `PREVCLOSE` float NOT NULL,
  `TOTTRDQTY` int(11) NOT NULL,
  `GAIN` float DEFAULT NULL,
  `TIMESTAMP` date DEFAULT NULL,
  `SCRIP_ID` int(11) DEFAULT NULL,
  `CREATED_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID_idx` (`SCRIP_ID`),
  CONSTRAINT `ID` FOREIGN KEY (`SCRIP_ID`) REFERENCES `SCRIP` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=6268 DEFAULT CHARSET=latin1;