<?php
 // module/Stocks/view/stocks/stocks/index.phtml:

 $title = 'My Stocks';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('stocks', array('action'=>'add'));?>">Add new stocks</a>
 </p>


<table class="table">
<tr>
    <th>Id</th>
   <th>Symbol</th>
    <th>Series</th>
    <th>Last</th>
    <th>Previous Close</th>
    <th>Total Traded Quantity</th>
         <th>Gain</th>
         <th>Timestamp</th>
         <th>Scrip Id</th>
         <th>Created Time</th>
</tr>
<?php foreach ($stocks as $stock) : ?>
<tr>
    <td><?php echo $this->escapeHtml($stock->id);?></td>
    <td><a href="<?php echo $this->url('stocks',
            array('action'=>'now', 'symbol' => $stock->symbol));?>">
            <?php echo $this->escapeHtml($stock->symbol);?></a></td>
    <td><?php echo $this->escapeHtml($stock->series);?></td>
    <td><?php echo $this->escapeHtml($stock->last);?></td>
    <td><?php echo $this->escapeHtml($stock->prevclose);?></td>
    <td><?php echo $this->escapeHtml($stock->tottrdqty);?></td>
         <td><?php echo $this->escapeHtml($stock->gain);?></td>
         <td><?php echo $this->escapeHtml($stock->timestamp);?></td>
         <td><?php echo $this->escapeHtml($stock->scrip_id);?></td>
         <td><?php echo $this->escapeHtml($stock->created_time);?></td>
</tr>
<?php endforeach; ?>
</table>