<?php
 // module/Stocks/view/stocks/stocks/index.phtml:

 $title = 'My Stocks';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
 <br />
     <a href="<?php echo $this->url('stocks', array('action'=>'add'));?>">Add new stocks</a>
 </p>

 <p>
 <?php
 if(empty($stocks)){
     echo " <br/> <h4><strong> Found no stocks for yesterday. <br /><br /> 
     Please click <a href=".$this->url('stocks', array('action'=>'add')). ">here </a>". " to load the latest data from NSE into the database.</strong></h4>";
 }else
 echo " Found ". $this->escapeHtml($stocks->count()). " stocks ";?>
<br/>
 </p>
<br/>
 
</table>